language: ruby
rvm:
  - 2.7

script: ./scripts/ci

branches:
  only:
  - master
  - gh-pages # test gh-pages branch
  - /pages-(.*)/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speed up html-proofer install

sudo: false

cache: bundler
