title:              "Dmitry Salahutdinov"
description:        "Dmitry Salahutdinov personal website"
author_name:        "Dmitry Salahutdinov"
logo_url:           assets/images/me.jpg

# Site Settings
url:                https://dsalahutdinov.github.io
permalink:          /:title
timezone:           Asia/Yekaterinburg
mathjax:            true

highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
