version: '3.4'

services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    image: dsalahutdinov.github.io:0.1.0
    volumes:
      - .:/app:cached
      - bundle:/bundle
    tmpfs:
      - /tmp

  runner:
    <<: *app
    stdin_open: true
    tty: true
    command: /bin/bash

  server:
    <<: *app
    stdin_open: true
    tty: true
    command: bundle exec jekyll serve --host 0.0.0.0
    ports:
      - '4000:4000'
volumes:
  bundle:
